module.exports = {
    TBL_CONTACTS_MASTER: 'ezb_wa_contacts',
    TBL_SYSTEM_CONFIG_MASTER: 'ezb_system_config',
    TBL_TEMPLATE_MASTER: 'ezb_wa_templates',
    TBL_MEDIA_MASTER: 'ezb_wa_media',
    TBL_REQUEST_MASTER: 'ezb_message_request_master',
    TBL_MESSAGE_REQUEST_MASTER: 'ezb_message_request_master',
    TBL_MESSAGE_SENT_MASTER: 'ezb_message_sent_master',
    TBL_API_KEYS_MASTER: 'ezb_wa_api_keys',
    TBL_USERS_MASTER: 'ezb_users',
    TBL_TEMPLATE_MASTER: 'ezb_wa_templates',
    TBL_WA_MSG_SETTINGS_MASTER: 'ezb_wa_msg_settings',
    TBL_WA_MEDIA_MASTER: 'ezb_wa_media',
    TBL_SYSTEM_CONFIG_MASTER: 'ezb_system_config',
    TBL_CAMPAIGN_MASTER: 'ezb_wa_campaign_master',
    TBL_CUSTOM_RATE_MASTER: 'ezb_wa_customize_rate',
    TBL_DEFAULT_RATE_MASTER: 'ezb_wa_rate_master',
    TBL_SUBSCRIPTION_MASTER: 'ezb_subscription_master',
    TBL_FLOWBUILDER_MASTER: 'ezb_flowbuilder_master',
    TBL_FLOWBUILDER_NODE: 'ezb_flowbuilder_node',
    TBL_FLOWBUILDER_NODE_OPTION: 'ezb_flowbuilder_node_option',
    TBL_FLOWBUILDER_SESSION: 'ezb_flowbuilder_session',
    TBL_FLOWBUILDER_ATTRIBUTE: 'ezb_flowbuilder_attributes',
    TBL_NON_CATALOG_MASTER: 'ezb_non_catalog_master',
    TBL_PURCHASE_MASTER: 'ezb_non_catalog_purchase_master',
    TBL_NON_CATALOG_PRODUCT_COMMON_DETAILS: 'ezb_non_catalog_product_common_details',
    TBL_PAYMENT_GATEWAY_DETAILS: 'ezb_payment_gateway_master',
    TBL_ORDER_DETAILS_MASTER: 'ezb_order_details_master',
    TBL_CATALOG_MASTER: 'ezb_catlogue_master',
    TBL_FAILED_CALLBACK_LOGS: 'ezb_failed_callback_logs'

};