module.exports = {
    TBL_CONTACTS_MASTER: 'ezb_wa_contacts',
    TBL_SYSTEM_CONFIG_MASTER: 'ezb_system_config',
    TBL_TEMPLATE_MASTER: 'ezb_wa_templates',
    TBL_MEDIA_MASTER: 'ezb_wa_media',
    TBL_REQUEST_MASTER: 'ezb_message_request_master',
    TBL_MESSAGE_REQUEST_MASTER: 'ezb_message_request_master',
    TBL_MESSAGE_SENT_MASTER: 'ezb_message_sent_master',
    TBL_API_KEYS_MASTER: 'ezb_wa_api_keys',
    TBL_USERS_MASTER: 'ezb_users',
    TBL_TEMPLATE_MASTER: 'ezb_wa_templates',
    TBL_WA_MSG_SETTINGS_MASTER: 'ezb_wa_msg_settings',
    TBL_WA_MEDIA_MASTER: 'ezb_wa_media',
    TBL_SYSTEM_CONFIG_MASTER: 'ezb_system_config',
    TBL_CAMPAIGN_MASTER: 'ezb_wa_campaign_master',
    TBL_NONWHATSAPP_MASTER: 'ezb_wa_non_whatsapp_contacts',
    TBL_SETTINGS_MASTER: 'ezb_wa_msg_settings',
    TBL_INVALID_CONTACTS_MASTER: 'ezb_wa_invalid_contacts',
    TBL_TEMP_CONTACTS_MASTER:'ezb_wa_temp_contacts',
    
}